[2024-06-06 23:16:48,343: INFO: main: Welcome to our custom logging]
[2024-06-08 01:37:32,666: INFO: common: yaml file: config\config.yaml load sucessfully]
[2024-06-08 01:37:32,667: INFO: common: yaml file: params.yaml load sucessfully]
[2024-06-08 01:55:51,497: INFO: main: Welcome to our custom logging]
[2024-06-08 01:55:51,497: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-08 01:55:51,498: INFO: common: yaml file: config\config.yaml load sucessfully]
[2024-06-08 01:55:51,499: INFO: common: yaml file: params.yaml load sucessfully]
[2024-06-08 01:55:51,499: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\utils\common.py", line 31, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\myenv\Lib\site-packages\box\box.py", line 296, in __init__
    raise BoxValueError("First argument must be mapping or iterable")
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 11, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\config\configuration.py", line 13, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\myenv\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\utils\common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-06-08 13:20:26,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-08 13:20:26,788: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-08 13:23:04,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-08 13:23:04,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-08 13:29:00,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-08 13:29:00,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-08 13:29:00,180: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-08 13:29:00,182: INFO: common: created directory at: artifacts]
[2024-06-08 13:29:00,185: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-08 13:29:00,781: INFO: 1624685146: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FDE2:3280F0:2064AEB:2462850:666494DB
Accept-Ranges: bytes
Date: Sat, 08 Jun 2024 17:29:00 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4663-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1717867741.519811,VS0,VE98
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7ff57c5bd8d5c1dbadae16283e3a6492bc405852
Expires: Sat, 08 Jun 2024 17:34:00 GMT
Source-Age: 0

]
[2024-06-08 13:31:11,568: INFO: main: Welcome to our custom logging]
[2024-06-08 13:31:11,570: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-08 13:31:11,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-08 13:31:11,583: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-08 13:31:11,584: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-08 13:31:11,584: INFO: common: created directory at: artifacts]
[2024-06-08 13:31:11,584: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-08 13:31:11,585: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-06-08 13:31:11,589: INFO: main: >>>>>> stage Data Ingestion stage commpleted <<<<<<

X==========X]
[2024-06-09 15:24:58,176: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:24:58,348: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 15:24:58,370: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 15:24:58,373: INFO: common: created directory at: artifacts]
[2024-06-09 15:24:58,375: INFO: common: created directory at: artifacts/data_validation]
[2024-06-09 15:26:37,103: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:26:37,108: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 15:26:37,115: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 15:26:37,118: INFO: common: created directory at: artifacts]
[2024-06-09 15:26:37,120: INFO: common: created directory at: artifacts/data_validation]
[2024-06-09 15:27:04,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 15:27:04,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 15:27:04,270: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 15:27:04,272: INFO: common: created directory at: artifacts]
[2024-06-09 15:27:04,275: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-09 15:27:04,277: INFO: 2366278714: File already exists of size: ~ 23 KB]
[2024-06-09 18:56:53,340: INFO: main: Welcome to our custom logging]
[2024-06-09 18:56:53,344: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 18:56:53,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 18:56:53,350: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 18:56:53,367: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 18:56:53,395: INFO: common: created directory at: artifacts]
[2024-06-09 18:56:53,395: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-09 18:56:53,980: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7B03:290038:2A86DCE:2FA2CF8:66663330
Accept-Ranges: bytes
Date: Sun, 09 Jun 2024 22:56:52 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4641-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1717973813.642355,VS0,VE60
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: a06777f639270d4bc3b696a8f413b0011fccd57d
Expires: Sun, 09 Jun 2024 23:01:52 GMT
Source-Age: 0

]
[2024-06-09 18:56:54,011: INFO: main: >>>>>> stage Data Ingestion stage commpleted <<<<<<

X==========X]
[2024-06-09 19:01:59,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:01:59,319: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 19:01:59,326: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 19:01:59,328: INFO: common: created directory at: artifacts]
[2024-06-09 19:01:59,332: INFO: common: created directory at: artifacts/data_validation]
[2024-06-09 19:04:07,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:04:07,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 19:04:07,345: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 19:04:07,347: INFO: common: created directory at: artifacts]
[2024-06-09 19:04:07,349: INFO: common: created directory at: artifacts/data_validation]
[2024-06-09 19:20:03,612: INFO: main: Welcome to our custom logging]
[2024-06-09 19:20:03,613: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 19:20:03,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:20:03,618: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 19:20:03,620: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 19:20:03,621: INFO: common: created directory at: artifacts]
[2024-06-09 19:20:03,666: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-09 19:20:04,460: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7B03:290038:2A86DCE:2FA2CF8:66663330
Accept-Ranges: bytes
Date: Sun, 09 Jun 2024 23:20:03 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4638-BOS
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1717975203.045129,VS0,VE137
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 486135c74cefefcb24db2b3a3d0314f75272a59c
Expires: Sun, 09 Jun 2024 23:25:03 GMT
Source-Age: 0

]
[2024-06-09 19:20:04,486: INFO: main: >>>>>> stage Data Ingestion stage commpleted <<<<<<

X==========X]
[2024-06-09 19:20:04,486: INFO: main: >>>>>> stage Data Validation Stage started <<<<<<]
[2024-06-09 19:20:04,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:20:04,490: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 19:20:04,492: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 19:20:04,494: INFO: common: created directory at: artifacts]
[2024-06-09 19:20:04,496: INFO: common: created directory at: artifacts/data_validation]
[2024-06-09 19:20:04,581: INFO: main: >>>>>> stage Data Validation Stage completed <<<<<<

X==========X]
[2024-06-09 19:53:15,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 19:53:15,365: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 19:53:15,369: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 19:53:15,370: INFO: common: created directory at: artifacts]
[2024-06-09 19:53:15,372: INFO: common: created directory at: artifacts/data_transformation]
[2024-06-09 19:53:15,561: INFO: 2797779166: splited data to training and test sets]
[2024-06-09 19:53:15,562: INFO: 2797779166: (1199, 12)]
[2024-06-09 19:53:15,563: INFO: 2797779166: (400, 12)]
[2024-06-09 20:44:48,035: INFO: main: Welcome to our custom logging]
[2024-06-09 20:44:48,049: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 20:44:48,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 20:44:48,052: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 20:44:48,054: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 20:44:48,055: INFO: common: created directory at: artifacts]
[2024-06-09 20:44:48,056: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-09 20:44:48,373: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 12, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 17, in download_file
    filename, headers =request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-09 21:02:21,853: INFO: main: Welcome to our custom logging]
[2024-06-09 21:02:21,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-09 21:02:21,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-09 21:02:21,867: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-09 21:02:21,868: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-09 21:02:21,869: INFO: common: created directory at: artifacts]
[2024-06-09 21:02:21,881: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-09 21:02:22,442: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 13, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 17, in download_file
    filename, headers =request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 17:16:34,186: INFO: main: Welcome to our custom logging]
[2024-06-11 17:16:34,199: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 17:16:34,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 17:16:34,231: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 17:16:34,240: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 17:16:34,241: INFO: common: created directory at: artifacts]
[2024-06-11 17:16:34,242: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 17:16:34,665: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 13, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 17, in download_file
    filename, headers =request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 17:23:40,675: INFO: main: Welcome to our custom logging]
[2024-06-11 17:23:40,682: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 17:23:40,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 17:23:40,687: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 17:23:40,694: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 17:23:40,695: INFO: common: created directory at: artifacts]
[2024-06-11 17:23:40,696: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 17:23:41,127: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 13, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 17, in download_file
    filename, headers =request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 17:24:04,935: INFO: main: Welcome to our custom logging]
[2024-06-11 17:24:04,936: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 17:24:04,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 17:24:04,938: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 17:24:04,939: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 17:24:04,940: INFO: common: created directory at: artifacts]
[2024-06-11 17:24:04,943: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 17:24:05,173: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 13, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 17, in download_file
    filename, headers =request.urlretrieve(
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 17:25:38,555: INFO: main: Welcome to our custom logging]
[2024-06-11 17:25:38,556: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 17:25:38,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 17:25:38,558: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 17:25:38,559: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 17:25:38,559: INFO: common: created directory at: artifacts]
[2024-06-11 17:25:38,560: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 17:25:38,860: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 13, in <module>
    obj.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 17:36:06,353: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 17:36:06,368: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 17:36:06,384: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 17:36:06,387: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 17:36:06,389: INFO: common: created directory at: artifacts]
[2024-06-11 17:36:06,389: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 17:36:06,724: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 21:02:11,612: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 21:02:11,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:02:11,651: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:02:11,656: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:02:11,658: INFO: common: created directory at: artifacts]
[2024-06-11 21:02:11,658: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 21:02:12,134: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 21:05:23,943: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 21:05:23,961: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:05:23,964: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:05:23,966: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:05:23,967: INFO: common: created directory at: artifacts]
[2024-06-11 21:05:23,967: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 21:05:24,571: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6A58:1DAEBD:A4AE0E:B7D4F9:6668F452
Accept-Ranges: bytes
Date: Wed, 12 Jun 2024 01:05:23 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4690-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1718154324.524273,VS0,VE83
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 020b91868c64c9d4db7962dc11e76e5705209efd
Expires: Wed, 12 Jun 2024 01:10:23 GMT
Source-Age: 0

]
[2024-06-11 21:05:24,621: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-11 21:05:24,622: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-06-11 21:05:24,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:05:24,627: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:05:24,632: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:05:24,635: INFO: common: created directory at: artifacts]
[2024-06-11 21:05:24,636: INFO: common: created directory at: artifacts/data_validation]
[2024-06-11 21:05:24,830: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-06-11 21:05:24,831: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-06-11 21:05:24,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:05:24,859: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:05:24,863: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:05:24,864: INFO: common: created directory at: artifacts]
[2024-06-11 21:05:24,864: INFO: common: created directory at: artifacts/data_transformation]
[2024-06-11 21:05:24,999: INFO: data_transformation: Splited data into training and test sets]
[2024-06-11 21:05:25,001: INFO: data_transformation: (1199, 12)]
[2024-06-11 21:05:25,002: INFO: data_transformation: (400, 12)]
[2024-06-11 21:05:25,018: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-06-11 21:07:24,468: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 21:07:24,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:07:24,473: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:07:24,475: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:07:24,475: INFO: common: created directory at: artifacts]
[2024-06-11 21:07:24,476: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 21:07:24,839: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 21:08:15,151: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 21:08:15,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:08:15,153: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:08:15,154: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:08:15,155: INFO: common: created directory at: artifacts]
[2024-06-11 21:08:15,155: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 21:08:15,424: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\main.py", line 11, in <module>
    data_ingestion.main()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "D:\MY Work\end-to-end-ML-project-with-MLFlow\src\mlProject\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\parjita\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-06-11 21:11:27,419: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-11 21:11:27,423: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:11:27,424: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:11:27,425: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:11:27,426: INFO: common: created directory at: artifacts]
[2024-06-11 21:11:27,426: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-11 21:11:28,121: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 321F:1EB0B9:A8D166:BC08C2:6668F5BA
Accept-Ranges: bytes
Date: Wed, 12 Jun 2024 01:11:27 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4659-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1718154687.003698,VS0,VE140
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 29c996e0a36823d25695fcea48f6554a199bd263
Expires: Wed, 12 Jun 2024 01:16:27 GMT
Source-Age: 0

]
[2024-06-11 21:11:28,150: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-11 21:11:28,150: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-06-11 21:11:28,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:11:28,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:11:28,159: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:11:28,160: INFO: common: created directory at: artifacts]
[2024-06-11 21:11:28,185: INFO: common: created directory at: artifacts/data_validation]
[2024-06-11 21:11:28,312: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-06-11 21:11:28,313: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-06-11 21:11:28,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-11 21:11:28,326: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-11 21:11:28,331: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-11 21:11:28,332: INFO: common: created directory at: artifacts]
[2024-06-11 21:11:28,334: INFO: common: created directory at: artifacts/data_transformation]
[2024-06-11 21:11:28,395: INFO: data_transformation: Splited data into training and test sets]
[2024-06-11 21:11:28,396: INFO: data_transformation: (1199, 12)]
[2024-06-11 21:11:28,396: INFO: data_transformation: (400, 12)]
[2024-06-11 21:11:28,397: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-06-12 00:11:36,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 00:11:36,806: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 00:11:36,821: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 00:11:36,825: INFO: common: created directory at: artifacts]
[2024-06-12 00:17:39,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 00:17:40,003: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 00:17:40,005: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 00:17:40,007: INFO: common: created directory at: artifacts]
[2024-06-12 00:17:40,013: INFO: common: created directory at: artifacts/model_trainer]
[2024-06-12 00:17:47,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 00:17:47,620: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 00:17:47,625: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 00:17:47,626: INFO: common: created directory at: artifacts]
[2024-06-12 00:17:47,627: INFO: common: created directory at: artifacts/model_trainer]
[2024-06-12 13:32:42,988: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-12 13:32:42,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:32:43,000: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:32:43,009: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:32:43,010: INFO: common: created directory at: artifacts]
[2024-06-12 13:32:43,010: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-12 13:32:43,017: INFO: data_ingestion: File already exists of size: ~ 23 KB]
[2024-06-12 13:32:43,042: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-12 13:32:43,042: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-06-12 13:32:43,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:32:43,045: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:32:43,047: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:32:43,048: INFO: common: created directory at: artifacts]
[2024-06-12 13:32:43,048: INFO: common: created directory at: artifacts/data_validation]
[2024-06-12 13:32:43,114: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-06-12 13:32:43,115: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-06-12 13:32:43,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:32:43,128: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:32:43,129: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:32:43,130: INFO: common: created directory at: artifacts]
[2024-06-12 13:32:43,130: INFO: common: created directory at: artifacts/data_transformation]
[2024-06-12 13:32:43,184: INFO: data_transformation: Splited data into training and test sets]
[2024-06-12 13:32:43,185: INFO: data_transformation: (1199, 12)]
[2024-06-12 13:32:43,185: INFO: data_transformation: (400, 12)]
[2024-06-12 13:32:43,186: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-06-12 13:34:40,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:34:40,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:34:40,134: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:34:40,135: INFO: common: created directory at: artifacts]
[2024-06-12 13:34:40,144: INFO: common: created directory at: artifacts/model_trainer]
[2024-06-12 13:46:20,470: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-12 13:46:20,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:46:20,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:46:20,491: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:46:20,502: INFO: common: created directory at: artifacts]
[2024-06-12 13:46:20,504: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-12 13:46:21,009: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 8986:D1E8F:1373C17:15A6D70:6669DEEA
Accept-Ranges: bytes
Date: Wed, 12 Jun 2024 17:46:19 GMT
Via: 1.1 varnish
X-Served-By: cache-bos4644-BOS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1718214380.533417,VS0,VE117
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3c8926d89e3d0dd300c999390339413ade195430
Expires: Wed, 12 Jun 2024 17:51:19 GMT
Source-Age: 0

]
[2024-06-12 13:46:21,029: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-12 13:46:21,030: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-06-12 13:46:21,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:46:21,034: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:46:21,036: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:46:21,038: INFO: common: created directory at: artifacts]
[2024-06-12 13:46:21,040: INFO: common: created directory at: artifacts/data_validation]
[2024-06-12 13:46:21,162: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-06-12 13:46:21,163: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-06-12 13:46:21,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:46:21,169: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:46:21,170: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:46:21,171: INFO: common: created directory at: artifacts]
[2024-06-12 13:46:21,172: INFO: common: created directory at: artifacts/data_transformation]
[2024-06-12 13:46:21,286: INFO: data_transformation: Splited data into training and test sets]
[2024-06-12 13:46:21,287: INFO: data_transformation: (1199, 12)]
[2024-06-12 13:46:21,287: INFO: data_transformation: (400, 12)]
[2024-06-12 13:46:21,301: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-06-12 13:46:21,301: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-06-12 13:46:21,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-12 13:46:21,304: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-12 13:46:21,306: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-06-12 13:46:21,307: INFO: common: created directory at: artifacts]
[2024-06-12 13:46:21,307: INFO: common: created directory at: artifacts/model_trainer]
[2024-06-12 13:46:21,437: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
